package dev.synapse.billing.invoicing;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.springframework.stereotype.Component;

/**
 * Framework-default invoice PDF (reference: {@code billing/invoice_pdf.py}).
 *
 * <p>Self-contained: OpenPDF with the core Helvetica fonts (no embedding
 * licence, no system deps), A4 portrait in mm. Sections in the reference's
 * order: header, bill-to, meta, line table, totals, payment instructions.
 * Core fonts are latin-1, so text is sanitised at the boundary exactly as the
 * reference does — the visible content matches, the byte layout does not.
 */
@Component
public class InvoicePdf {

    private static final float MM = 72f / 25.4f;
    private static final float MARGIN = 18 * MM;

    private static final Color INK = new Color(24, 24, 27);        // zinc-900
    private static final Color MUTED = new Color(113, 113, 122);   // zinc-500
    private static final Color HAIRLINE = new Color(228, 228, 231);// zinc-200
    private static final Color HEADER_FILL = new Color(244, 244, 245);

    private static final Map<String, String> SYMBOLS = Map.of("PHP", "PHP ", "USD", "USD ", "EUR", "EUR ");
    private static final DateTimeFormatter DAY = DateTimeFormatter.ofPattern("MMM dd, yyyy", Locale.US).withZone(ZoneOffset.UTC);

    /** Latin-1 replacements the reference applies before handing text to the core font. */
    private static final Map<String, String> REPLACEMENTS = Map.of(
        "—", "-", "–", "-", "‘", "'", "’", "'",
        "“", "\"", "”", "\"", "•", "*", "₱", "PHP ");

    public byte[] render(Invoice invoice, List<InvoiceLine> lines, String orgName, String billingEmail, String payToInstructions) {
        Document document = new Document(PageSize.A4, MARGIN, MARGIN, MARGIN, MARGIN);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        String number = invoice.number() != null ? invoice.number() : invoice.id().toString();
        try {
            PdfWriter.getInstance(document, out);
            document.addTitle("Invoice " + latin1(number));
            document.open();
            header(document, number);
            billTo(document, orgName, billingEmail);
            meta(document, invoice);
            table(document, lines, invoice.currency());
            totals(document, invoice);
            instructions(document, invoice, payToInstructions);
            document.close();
        } catch (DocumentException e) {
            throw new IllegalStateException("Invoice PDF rendering failed for " + invoice.id(), e);
        }
        return out.toByteArray();
    }

    // ── Sections ─────────────────────────────────────────────────────────────────

    private void header(Document document, String number) throws DocumentException {
        document.add(line(latin1("Synapse"), bold(18), INK, Element.ALIGN_LEFT));
        document.add(line("Generated by the Synapse SaaS Framework", regular(9), MUTED, Element.ALIGN_LEFT));
        document.add(spacer(6));
        document.add(line("INVOICE " + latin1(number), bold(14), INK, Element.ALIGN_RIGHT));
        document.add(rule(HAIRLINE));
        document.add(spacer(8));
    }

    private void billTo(Document document, String orgName, String billingEmail) throws DocumentException {
        PdfPTable table = borderless(new float[] {30, 132});
        table.addCell(cell("Billed to", regular(9), MUTED, Element.ALIGN_LEFT));
        table.addCell(cell(latin1(orgName), bold(10), INK, Element.ALIGN_LEFT));
        if (billingEmail != null && !billingEmail.isBlank()) {
            table.addCell(cell("", regular(9), MUTED, Element.ALIGN_LEFT));
            table.addCell(cell(latin1(billingEmail), regular(9), MUTED, Element.ALIGN_LEFT));
        }
        document.add(table);
        document.add(spacer(4));
    }

    private void meta(Document document, Invoice invoice) throws DocumentException {
        record Pair(String label, String value) {}
        java.util.List<Pair> pairs = new java.util.ArrayList<>();
        if (invoice.periodStart() != null && invoice.periodEnd() != null) {
            pairs.add(new Pair("Period", DAY.format(invoice.periodStart()) + " - " + DAY.format(invoice.periodEnd())));
        }
        if (invoice.issuedAt() != null) {
            pairs.add(new Pair("Issued", DAY.format(invoice.issuedAt())));
        }
        pairs.add(new Pair("Status", invoice.status().toUpperCase(Locale.ROOT)));

        float[] widths = new float[pairs.size()];
        java.util.Arrays.fill(widths, 1f);
        PdfPTable table = borderless(widths);
        pairs.forEach(p -> table.addCell(cell(p.label(), regular(9), MUTED, Element.ALIGN_LEFT)));
        pairs.forEach(p -> table.addCell(cell(latin1(p.value()), regular(9), INK, Element.ALIGN_LEFT)));
        document.add(table);
        document.add(spacer(10));
    }

    private void table(Document document, List<InvoiceLine> lines, String currency) throws DocumentException {
        PdfPTable table = new PdfPTable(new float[] {78, 24, 36, 36});
        table.setWidthPercentage(100);
        for (String label : List.of("Description", "Qty", "Unit price", "Amount")) {
            PdfPCell head = bordered(label, bold(9), MUTED);
            head.setBackgroundColor(HEADER_FILL);
            table.addCell(head);
        }
        if (lines.isEmpty()) {
            PdfPCell empty = bordered("No billable items this period", regular(9), INK);
            empty.setColspan(4);
            table.addCell(empty);
            document.add(table);
            return;
        }
        for (InvoiceLine line : lines) {
            Phrase description = new Phrase(latin1(truncate(line.description())), regular(9));
            if (line.metric() != null) {
                description.add(new Phrase("\n" + latin1(line.metric()), italic(7)));
            }
            PdfPCell descriptionCell = new PdfPCell(description);
            descriptionCell.setPadding(3);
            table.addCell(descriptionCell);
            table.addCell(bordered(grouped(line.quantity()), regular(9), INK));
            table.addCell(bordered(money(line.unitAmountCents(), currency), regular(9), INK));
            table.addCell(bordered(money(line.amountCents(), currency), regular(9), INK));
        }
        document.add(table);
    }

    private void totals(Document document, Invoice invoice) throws DocumentException {
        PdfPTable table = borderless(new float[] {50, 40});
        table.setHorizontalAlignment(Element.ALIGN_RIGHT);
        table.setWidthPercentage(50);
        table.addCell(cell("Subtotal", regular(9), MUTED, Element.ALIGN_LEFT));
        table.addCell(cell(money(invoice.subtotalCents(), invoice.currency()), regular(9), INK, Element.ALIGN_RIGHT));
        table.addCell(cell("Tax", regular(9), MUTED, Element.ALIGN_LEFT));
        table.addCell(cell(money(invoice.taxCents(), invoice.currency()), regular(9), INK, Element.ALIGN_RIGHT));
        table.addCell(cell("Total due", bold(11), INK, Element.ALIGN_LEFT));
        table.addCell(cell(money(invoice.totalCents(), invoice.currency()), bold(11), INK, Element.ALIGN_RIGHT));
        document.add(spacer(4));
        document.add(table);
        document.add(spacer(10));
    }

    private void instructions(Document document, Invoice invoice, String payTo) throws DocumentException {
        if ("paid".equals(invoice.status())) {
            String when = invoice.paidAt() == null ? "" : " - " + DAY.format(invoice.paidAt());
            document.add(line("PAID" + when, bold(10), INK, Element.ALIGN_LEFT));
            return;
        }
        if (payTo == null || payTo.isBlank()) {
            return;
        }
        document.add(line("Payment instructions", bold(9), MUTED, Element.ALIGN_LEFT));
        document.add(line(latin1(payTo), regular(9), INK, Element.ALIGN_LEFT));
    }

    // ── Primitives ───────────────────────────────────────────────────────────────

    private static Paragraph line(String text, Font font, Color colour, int alignment) {
        Font coloured = new Font(font);
        coloured.setColor(colour);
        Paragraph paragraph = new Paragraph(text, coloured);
        paragraph.setAlignment(alignment);
        return paragraph;
    }

    private static PdfPCell cell(String text, Font font, Color colour, int alignment) {
        Font coloured = new Font(font);
        coloured.setColor(colour);
        PdfPCell cell = new PdfPCell(new Phrase(text, coloured));
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setHorizontalAlignment(alignment);
        cell.setPadding(2);
        return cell;
    }

    private static PdfPCell bordered(String text, Font font, Color colour) {
        Font coloured = new Font(font);
        coloured.setColor(colour);
        PdfPCell cell = new PdfPCell(new Phrase(text, coloured));
        cell.setPadding(3);
        return cell;
    }

    private static PdfPTable borderless(float[] widths) {
        PdfPTable table = new PdfPTable(widths);
        table.setWidthPercentage(100);
        table.getDefaultCell().setBorder(Rectangle.NO_BORDER);
        return table;
    }

    private static Paragraph spacer(float points) {
        Paragraph paragraph = new Paragraph(" ", regular(1));
        paragraph.setSpacingAfter(points);
        return paragraph;
    }

    private static Paragraph rule(Color colour) {
        Paragraph paragraph = new Paragraph();
        com.lowagie.text.pdf.draw.LineSeparator separator = new com.lowagie.text.pdf.draw.LineSeparator(0.4f, 100, colour, Element.ALIGN_CENTER, 0);
        paragraph.add(separator);
        return paragraph;
    }

    private static Font regular(float size) {
        return FontFactory.getFont(FontFactory.HELVETICA, size);
    }

    private static Font bold(float size) {
        return FontFactory.getFont(FontFactory.HELVETICA_BOLD, size);
    }

    private static Font italic(float size) {
        return FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, size);
    }

    // ── Formatting (same output as the reference's helpers) ───────────────────────

    public static String money(long cents, String currency) {
        String symbol = SYMBOLS.getOrDefault(currency, currency + " ");
        return symbol + String.format(Locale.US, "%,.2f", cents / 100.0);
    }

    public static String grouped(long value) {
        return String.format(Locale.US, "%,d", value);
    }

    /** Core-font PDFs are latin-1: map what the reference maps, replace the rest. */
    public static String latin1(String text) {
        if (text == null) {
            return "";
        }
        String mapped = text;
        for (Map.Entry<String, String> entry : REPLACEMENTS.entrySet()) {
            mapped = mapped.replace(entry.getKey(), entry.getValue());
        }
        StringBuilder out = new StringBuilder(mapped.length());
        for (char c : mapped.toCharArray()) {
            out.append(c < 256 ? c : '?');
        }
        return out.toString();
    }

    /** The reference clips descriptions to 80 characters in the table cell. */
    private static String truncate(String description) {
        return description.length() <= 80 ? description : description.substring(0, 80);
    }
}
